name: Test deployment

on:
  push:
    branches:
      - '*'
    # Review gh actions docs if you want to further define triggers, paths, etc
    #
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Install, lint and build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
      - name: Test build website
        run: npm run build
